# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 11:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InverseIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('index', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='inverseindex',
            unique_together=set([('term', 'index')]),
        ),
    ]
