# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-25 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inverseindex',
            name='index',
        ),
        migrations.AddField(
            model_name='inverseindex',
            name='index',
            field=models.ManyToManyField(to='dataapp.Provenance'),
        ),
    ]
