# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dataapp', '0003_auto_20170526_1442'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inverseindex',
            unique_together=set([('term', 'index')]),
        ),
    ]
