# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Closeness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='DEFAULT_TERM', max_length=100)),
                ('close_to', models.CharField(default='DEFAULT_CLOSETO', max_length=100)),
                ('closeness', models.DecimalField(decimal_places=10, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_app.Paragraph')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='DEFAULT_TITLE', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='DEFAULT_TOKEN', max_length=100)),
                ('pos_tag', models.CharField(default='DEFAULT_TAG', max_length=5)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_app.Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='paragraph',
            name='text',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_app.Text'),
        ),
    ]
