# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('text_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Closeness',
            new_name='ClosenessModel',
        ),
        migrations.RenameModel(
            old_name='Paragraph',
            new_name='ParagraphModel',
        ),
        migrations.RenameModel(
            old_name='Text',
            new_name='TextModel',
        ),
        migrations.RenameModel(
            old_name='Token',
            new_name='TokenModel',
        ),
        migrations.RemoveField(
            model_name='sentence',
            name='paragraph',
        ),
        migrations.AlterField(
            model_name='tokenmodel',
            name='sentence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_app.SentenceModel'),
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.AddField(
            model_name='sentencemodel',
            name='paragraph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_app.ParagraphModel'),
        ),
    ]
