# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queryapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsalias',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
